name: data_vis
channels:
  - conda-forge
dependencies:
  - circlify=0.15.0
  - ipython=8.16.1
  - ipywidgets=8.1.1
  - jupyterlab=4.0.6
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.0
  - jupyterlab_widgets=3.0.9
  - nbclient=0.8.0
  - nbconvert-core=7.9.2
  - nbformat=5.9.2
  - notebook=7.0.4
  - notebook-shim=0.2.3
  - numpy=1.26.0
  - openpyxl=3.1.2
  - openssl=3.1.4
  - pandas=2.1.1
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - plotly=5.17.0
  - psutil=5.9.5
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.10
  - pyyaml=6.0.1
  - scipy=1.11.3
  - setuptools=68.2.2
  - yaml=0.2.5
